export interface AgencyInfo {
  name: string;
  limit: string;
  rate: string;
  period: string;
  monthlyPayment: string;
}

export interface ReportData {
  businessName: string;
  ceoName: string;
  businessNumber: string;
  openingDate: string;
  industry: string;
  businessAge: string;
  address: string;
  creditScore: number;
  creditGrade: string;
  creditComment: string;
  creditScorePercentage: number;
  requiredFunding: string;
  riskLevel: string;
  keyFinding1: string;
  keyFinding2: string;
  keyFinding3: string;
  sales2022: number;
  sales2023: number;
  sales2024: number;
  sales2025: number;
  growthRate: string;
  totalRevenue: string;
  cagr: string;
  cagrPeriod: string;
  stabilityScore: string;
  stabilityDescription: string;
  reviewScore: string;
  reviewDescription: string;
  totalDebt: string;
  loanBalance: string;
  guaranteeBalance: string;
  debt1stTier: string;
  debt1stTierPct: number;
  debt2ndTier: string;
  debt2ndTierPct: number;
  debtPublic: string;
  debtPublicPct: number;
  dti2024: string;
  dti2024Status: '안전' | '주의' | '위험';
  dti3Year: string;
  dti3YearStatus: '안전' | '주의' | '위험';
  dtiInterpretation: string;
  diagnosisResult: string;
  currentRate: string;
  improvedRate: string;
  rateDiff: string;
  currentInterest: string;
  improvedInterest: string;
  interestSavings: string;
  executionPlan: { institution: string; amount: string }[];
  totalExpectedAmount: string;
  recommendation1: string;
  recommendation2: string;
  recommendation3: string;
  agencies: AgencyInfo[];
  totalExpectedFunding: string;
  fundingPeriod: string;
  consultantName: string;
  consultantPhone: string;
  consultantEmail: string;
  reportDate: string;
  validUntil: string;
}
